name: exhaustive

on:
  pull_request:
    branches: [main, master]
    types: [labeled, opened, synchronize, reopened]
  push:
    branches: [main, master]
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deny-audit:
    name: deny + audit
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'exhaustive')
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - uses: taiki-e/install-action@a6b2e2dcd845ddd7f509ce4f3ed3d922b80cc5d9 # v2.84.0
        with:
          tool: cargo-deny@0.18,cargo-audit@0.21
      - run: cargo deny check
      - run: cargo audit

  machete:
    name: unused dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'exhaustive')
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - uses: taiki-e/install-action@a6b2e2dcd845ddd7f509ce4f3ed3d922b80cc5d9 # v2.84.0
        with:
          tool: cargo-machete@0.8
      - run: cargo machete
